### ISSUE TITLE
Add support for OTel tracing

### ISSUE THREAD

**Issue by marclop** [elastic/go-docappender#45]
## Description

The appender currently accepts an `*apm.Tracer` in its config and uses it to trace flushes to Elasticsearch. 

https://github.com/elastic/go-docappender/blob/96531c337391cc64310d9ba6562a2b39f214015e/config.go#L38-L42

To align our general efforts, we should consider using OTel tracing, which also aligns with #37.

**Comment by axw** [comment]
I apparently missed the news that go-elasticsearch has OTel tracing now. We should probably be relying on that: https://github.com/elastic/go-elasticsearch/blob/264743bde3a913cb8aa84160fcef7d5551c44696/elasticsearch.go#L117-L132

**Comment by endorama** [comment]
Is this task related to adding support to Otel in parallel with current tracing or should the current tracer be removed entirely? In the latter, it looks like a breaking change to me. I consider part of this task a release including the new tracer, do you agree on the breaking change?

**Comment by axw** [comment]
@endorama yes, it would be breaking. I think we should add (opt-in) OTel tracing in parallel with the existing Elastic APM tracing, and later follow up with removing Elastic APM instrumentation.

**Comment by endorama** [comment]
PR for supporting otel tracing is ready for review in https://github.com/elastic/go-docappender/pull/182

Following up on this @axw comment
> I apparently missed the news that go-elasticsearch has OTel tracing now. We should probably be relying on that: https://github.com/elastic/go-elasticsearch/blob/264743bde3a913cb8aa84160fcef7d5551c44696/elasticsearch.go#L117-L132

To my understanding in `go-docappender` we receive an already instantiated client (in `New(client esapi.Transport, ...)`. Due to this is not `go-docappender` responsibility to leverage `go-elasticsearch` instrumentation but it's caller responsibility to provide a client with instrumentation initialized. 
The changes in the linked PR are to add the span from `Appender.flush`, which would otherwise be lost, but do not include tracing Elasticsearch client, as that comes from the client.

**Comment by endorama** [comment]
I created https://github.com/elastic/go-docappender/issues/184 to follow up on removing the APM tracer marked as deprecated.
